export default {
  SET_IMAGE: 'setImage',
  INIT_COORDINATES: 'initCoordinates',
  SET_COORDINATES: 'setCoordinates',
  ADD_HIGHLIGHT: 'addHighlight',
  REMOVE_HIGHLIGHT: 'removeHighlight',
  SELECT_HIGHLIGHT: 'selectHighlight',
  SHIFT_HIGHLIGHT: 'shiftHighlight',
  UNSHIFT_HIGHLIGHT: 'unshiftHighlight',
  CHANGE_SELECTED_ITEM_LABEL: 'changeSelectedItemLabel',
  ZOOM: 'zoom',
  SET_DRAGGING_ELEMENT: 'setDraggingElement',
  FETCH_TREE_DATA: 'fetchTreeData',
  SET_TREE_DATA: 'setTreeData',
}
