name: PackTracker - Analyze webpack bundle

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Analyze webpack bundle
        uses: packtracker/report@2.2.0
        with:
          PT_PROJECT_TOKEN: ${{ secrets.PACKTRACKER_TOKEN }}
        env:
          PT_PROJECT_TOKEN: ${{ secrets.PACKTRACKER_TOKEN }}
          WEBPACK_CONFIG_PATH: "../../webpack.production.js"
